```{r}
#    https://shiny.posit.co/

library(shiny)
library(ggplot2)
library(tidyverse)
library(readxl)
library(patchwork)

# Import data and join tables.
ors_raw <- read_excel("app/data/or_survey_sim_final_2023-11-29.xlsx")
pde_raw <- read_excel("app/data/pde_sim_final_2023-11-29.xlsx")

# Map text responses to ordinal data.
num_map <- c(
    "Strongly agree" = 5,
    "Somewhat agree" = 4,
    "Neither agree nor disagree" = 3,
    "Somewhat disagree" = 2,
    "Strongly disagree" = 1,
    "Very much like me" = 5,
    "Mostly like me" = 4,
    "Somewhat like me" = 3,
    "Not much like me" = 2,
    "Not at all like me" = 1
)

chr_map <- c(
    "Y" = "Yes",
    "N" = "No"
)


ors_pde_raw <- merge(ors_raw, pde_raw) |>
    mutate(across(FIRST_GENERATION_IND, ~ recode(.x, !!!chr_map)))

ors_num <- ors_raw
ors_num[-1] <- ors_num[-1] |>
    mutate(across(everything(), ~ recode(.x, !!!num_map)))
ors_pde_num <- merge(ors_num, pde_raw)

# Full statement of each survey question.
ors_qs <- c(
    "Q4_1" = "I feel I belong at Binghamton University.",
    "Q4_2" = "I am ready to meet the academic challenges of Binghamton University.",
    "Q11_1" = "Binghamton University is concerned with my personal health/wellness.",
    "Q11_2" = "Binghamton University has a number of services available to help me be healthy at college.",
    "Q15_1" = "I feel like I have the resources to make me a financially responsible college student.",
    "Q15_2" = "I feel connected to the Binghamton University community.",
    "Q15_3" = "Binghamton University is a place where I am able to perform up to my full potential.",
    "Q15_4" = "I have found one or more communities or groups where I feel I belong at Binghamton University.",
    "Q15_5" = "I am ready to make friends at Binghamton University.",
    "Grit_1" = "New ideas and projects sometimes distract me from previous ones.",
    "Grit_2" = "Setbacks don’t discourage me.",
    "Grit_3" = "I have been obsessed with a certain idea or project for a short time but later lost interest.",
    "Grit_4" = "I am a hard worker.",
    "Grit_5" = "I often set a goal but later choose to pursue a different one.",
    "Grit_6" = "I have difficulty maintaining my focus on projects that take more than a few months to complete.",
    "Grit_7" = "I finish whatever I begin.",
    "Grit_8" = "I am diligent."
)

ors_kws <- c(
    "Q4_1: Belonging" = "Q4_1",
    "Q4_2: Academic Preparedness" = "Q4_2",
    "Q11_1: Wellness Concern" = "Q11_1",
    "Q11_2: Wellness Services" = "Q11_2",
    "Q15_1: Financial Resources" = "Q15_1",
    "Q15_2: Community Connection" = "Q15_2",
    "Q15_3: Full Potential" = "Q15_3",
    "Q15_4: Community Belonging" = "Q15_4",
    "Q15_5: Friends" = "Q15_5",
    "Grit_1: Distraction" = "Grit_1",
    "Grit_2: Setbacks" = "Grit_2",
    "Grit_3: Losing Interest" = "Grit_3",
    "Grit_4: Hard Worker" = "Grit_4",
    "Grit_5: Changing Goals" = "Grit_5",
    "Grit_6: Maintaining Focus" = "Grit_6",
    "Grit_7: Finishing" = "Grit_7",
    "Grit_8: Diligence" = "Grit_8"
)

q_response_order <- c(
    "Strongly agree",
    "Somewhat agree",
    "Neither agree nor disagree",
    "Somewhat disagree",
    "Strongly disagree"
)

grit_response_order <- c(
    "Very much like me",
    "Mostly like me",
    "Somewhat like me",
    "Not much like me",
    "Not at all like me"
)

# Survey questions associated with each topic.
topic_qs <- list(
    "Sociality" = c("Q4_1", "Q15_2", "Q15_4", "Q15_5"),
    "Wellness" = c("Q11_1", "Q11_2"),
    "Success" = c("Q4_2", "Q15_1", "Q15_3"),
    "Grit" = c("Grit_1", "Grit_2", "Grit_3", "Grit_4", "Grit_5", "Grit_6", "Grit_7", "Grit_8")
)
```

```{r}
# Implement Shiny UI
ui <- fluidPage(
    titlePanel("SAASE Orientation Survey: Explore the Data"),
    tabsetPanel(
        tabPanel("Free Exploration",
            sidebarLayout(
                # Sidebar for filtering data.
                sidebarPanel(
                    style = "min-height: 85vh;",
                    # Select topic
                    selectInput(
                        inputId = "free_q",
                        label = "Question:",
                        choices = names(ors_kws)
                    ),
                    # Select demographic to filter
                    selectInput(
                        inputId = "filt",
                        label = "Filter by:",
                        choices = c(
                            "--",
                            "Population" = "STUDENT_POPULATION_DESC",
                            "First Generation" = "FIRST_GENERATION_IND",
                            "Housing Type" = "HOUSING_TYPE",
                            "Living Community" = "COMMUNITY",
                            "College" = "COLLEGE_DESC"
                        )
                    ),
                    # Filter options
                    uiOutput("filt_val_ui"),
                    h5(HTML("<strong>Data Remaining:</strong>")),
                    uiOutput("curr_filts", style="font-size: 12px;"),
                    # Button to update the charts.
                    actionButton(
                        inputId = "free_load",
                        label = "Load Chart"
                    )
                ),
                mainPanel(
                    column(12, align="center",
                        h3(textOutput("free_title")),
                        plotOutput("free_pie", height=600)
                    )
                )
            )
        ),
        tabPanel("Analysis",
            sidebarLayout(
                sidebarPanel(
                    style = "height: 85vh;",
                    # Select topic
                    selectInput(
                        inputId = "stat_topic",
                        label = "Topic:",
                        choices = c("Sociality", "Wellness", "Success", "Grit")
                    ),
                    # Select demographic to filter
                    selectInput(
                        inputId = "stat_demo",
                        label = "Demographic:",
                        choices = c(
                            "Population" = "STUDENT_POPULATION_DESC",
                            "First Generation" = "FIRST_GENERATION_IND",
                            "Housing Type" = "HOUSING_TYPE",
                            "Living Community" = "COMMUNITY",
                            "College" = "COLLEGE_DESC"
                        ),
                    ),
                    # Button to update the charts.
                    actionButton(
                        inputId = "stat_load",
                        label = "Load Analysis"
                    )
                ),
                mainPanel(
                    fluidRow(
                        h3(textOutput("demo_title")),
                        plotOutput("demo_plot", height=400)
                    ),
                    fluidRow(
                        h3("stat data")
                    )
                )
            )
        )
    )
)

# Define Shiny server logic.
server <- function(input, output) {
    
    # Keep track of which filters are active.
    selected_filts <- reactiveValues(
        STUDENT_POPULATION_DESC = unique(ors_pde_raw$STUDENT_POPULATION_DESC),
        FIRST_GENERATION_IND = unique(ors_pde_raw$FIRST_GENERATION_IND),
        HOUSING_TYPE = unique(ors_pde_raw$HOUSING_TYPE),
        COMMUNITY = unique(ors_pde_raw$COMMUNITY),
        COLLEGE_DESC = unique(ors_pde_raw$COLLEGE_DESC)
    )
    
    # Render demographics plot
    output$demo_plot <- renderPlot({
        stat_topic <- eventReactive(input$stat_load, input$stat_topic)
        stat_demo <- eventReactive(input$stat_load, input$stat_demo)
        stat_qs <- topic_qs[[stat_topic()]]
        
        df_summary <- ors_pde_num |>
            select(all_of(stat_qs), stat_demo()) |>
            group_by(get(stat_demo())) |>
            summarise(
                avg = mean(rowMeans(across(all_of(stat_qs)), na.rm = TRUE)),
                sd = sd(rowMeans(across(all_of(stat_qs)), na.rm = TRUE)),  # Standard deviation
                n = n()
            ) |>
            mutate(se = sd / sqrt(n))
        
        colnames(df_summary)[1] <- stat_demo()
        output$demo_title = renderText({paste("Average ",stat_topic()," Responses")})
        ggplot(df_summary, aes(x = .data[[stat_demo()]], y = avg)) +
            geom_point(size = 3, color = "blue") +  # Plot the averages
            geom_errorbar(aes(ymin = avg - se, ymax = avg + se), width = 0.2, color = "black") +  # Error bars
            labs(x = NULL, y = "Average Response") +
            theme_bw() +
            scale_y_continuous(limits = c(3, 5)) +
            theme(
                axis.text.x = element_text(angle = 45, hjust = 1, size = 15))
        
    })
    
    # Update filtering options based on selected filter group.
    output$filt_val_ui <- renderUI({
        filt <- input$filt
        if (filt != "--") {
            col <- get(filt, envir = as.environment(ors_pde_raw))
            checkboxGroupInput(
                inputId = "filt_vals",
                label = "",
                choices = unique(col),
                selected = selected_filts[[filt]]
            )
        } else {
            NULL
        }
    })
    
    # Update selected_filters whenever filt_vals changes
    observeEvent(input$filt_vals, {
        filt <- input$filt
        if (filt != "None") {selected_filts[[filt]] <- input$filt_vals}
    })
    
    # Update data frame used for plotting when needed.
    filtered_data <- eventReactive(input$free_load, {
        q <- input$free_q
        df_filt <- ors_pde_raw |>
            select(get(ors_kws[q]), names(selected_filts)) |>
            filter(
                STUDENT_POPULATION_DESC %in% selected_filts[["STUDENT_POPULATION_DESC"]],
                FIRST_GENERATION_IND %in% selected_filts[["FIRST_GENERATION_IND"]],
                HOUSING_TYPE %in% selected_filts[["HOUSING_TYPE"]],
                COMMUNITY %in% selected_filts[["COMMUNITY"]],
                COLLEGE_DESC %in% selected_filts[["COLLEGE_DESC"]]
            )
        df_filt
    })
    
    # Render pie chart for a single question
    output$free_pie <- renderPlot({
        q <- eventReactive(input$free_load, input$free_q)
        qCol <- ors_kws[q()]
        output$free_title <- renderText({ors_qs[qCol]})
        df_filt <- filtered_data() |>
            select(get(qCol)) |>
            mutate(
                response = factor(get(qCol),
                levels = if (substr(qCol,1,1) != "Q") grit_response_order else q_response_order)
            ) |>
            count(response, .drop = FALSE)
        ggplot(df_filt, aes(x = "", y = n, fill = response)) + 
            geom_bar(stat = "identity") + 
            coord_polar("y", start = 0) +
            scale_fill_brewer(
                palette = "RdYlGn",
                direction = -1
            ) +
            labs(x = "", y = "") +
            theme_void() 
    })
    
    # Display data currently allowed by filters
    output$curr_filts <- renderUI({
        txt <- ""
        for (name in names(selected_filts)) {
            txt <- paste(txt, "<strong>",name,"</strong>", ":", paste(selected_filts[[name]], collapse=", "), "<br>")
        }
        HTML(paste(txt,"<br>"))
    })

}
```

```{r}
# Run the application 
shinyApp(ui, server)
```

